version: '3'
services:

  # a sample app with metrics enabled
  sample_web_app:
    container_name: mysamplewebapp
    build:
      context: sample_web_app/
    ports:
      - "8080:8080"
    healthcheck:
      test: curl -sS http://127.0.0.1:8080 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  # the Prometheus server
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.2.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - sample_web_app
    healthcheck:
      test: curl -sS http://127.0.0.1:9090 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  # Grafana for visualization
  grafana:
    image: grafana/grafana:5.1.0
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    healthcheck:
      test: curl -sS http://127.0.0.1:3000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
