global:
  scrape_interval: 3s

  external_labels:
    monitor: "example-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  
  - job_name: "metrics"
    static_configs:
      - targets: ["mysamplewebapp:8080"]
